#!/bin/bash
set -e

source $(dirname $0)/version

cd $(dirname $0)/..

PKG="rancher/confd"

rm -rf bin/*
mkdir -p bin

for platform in darwin linux windows; do \
  if [ $platform == windows ]; then extension=.exe; fi; \
  GOOS=$platform GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-s -w -X main.GitSHA=${GIT_SHA}" -o bin/confd-${VERSION}-$platform-amd64$extension; \
  if [ $platform == linux ]; then \
  GOOS=$platform GOARCH=arm CGO_ENABLED=0 go build -ldflags="-s -w -X main.GitSHA=${GIT_SHA}" -o bin/confd-${VERSION}-linux-arm; \
  GOOS=$platform GOARCH=arm64 CGO_ENABLED=0 go build -ldflags="-s -w -X main.GitSHA=${GIT_SHA}" -o bin/confd-${VERSION}-linux-arm64; \
  fi; \
done

sha256sum bin/* > bin/sha256sum.txt

cd bin/
ls
