name: Dapper CI on PR and Merge
run-name: Release ${{ github.ref_name }}

on:
  pull_request:
  push:
    branches:
      - release/v0.16

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: rancher/dapper:v0.6.0
    permissions:
      contents: read
    steps:
      - name: Fix the not-a-git-repository issue
        run: |
          apk -U add git
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
            go-version-file: go.mod
      - name: build with Dapper
        run: dapper ci