name: Release When Tagged
run-name: Release ${{ github.ref_name }}

on:
  push:
    tags: '*'

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: rancher/dapper:v0.6.0
    permissions:
      contents: read
    steps:
      - name: Fix the not-a-git-repository issue
        run: |
          apk -U add git
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - name: Checkout code
        uses: actions/checkout@v4
      - name: build with Dapper
        run: dapper ci
        
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: confd-build
          path: bin
          if-no-files-found: error
          overwrite: true

  create-release:
    runs-on: ubuntu-latest
    needs:
      - validate
    permissions:
      contents: write # needed for creating the GH release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIT_SHA: sha256
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download assets
        uses: actions/download-artifact@v4

      - name: Create GH release
        run: |
          if [[ ${{ github.ref_name }} == *"rc"*  || ${{ github.ref_name }} == *"alpha"* ]]; then
            gh release create ${{ github.ref_name }} --verify-tag --prerelease --latest=false --generate-notes confd-build/*
          else
            gh release create ${{ github.ref_name }} --verify-tag --latest --generate-notes confd-build/*
          fi